version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: clients-db
    restart: always
    environment:
      POSTGRES_USER: censudex
      POSTGRES_PASSWORD: censudex123
      POSTGRES_DB: clients_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: